### ISSUE TITLE
Quest Creator Readme Need Update

### ISSUE THREAD

**Issue by robw2000** [ExpeditionRPG/expedition-quest-creator#226]
The Quest Creator README seems to be out of date. In the "Now install the repo" section, the git repo name is incorrect. Also, there is a reference to a config.json file that is never defined. Is this something that the developer should already know about somehow? I am not familiar with it if that is the case!

This is a very interested and fun project. Thank you for creating it.

**Comment by toddmedema** [comment]
@robw2000 welcome to the community, and good point! I've updated the readme + added an `config-example.json` file to the repo. We haven't tested the installation steps on a clean machine in a while, so if you're willing to help us debug the process, that'd be very helpful :)

**Comment by robw2000** [comment]
I found a few more issues.

1. I see that some info about the config.json was added to the README. I still don't see the config-example.json file that is mentioned there in the repo. Maybe it didn't get committed?
2. The README says to run "sudo npm install -g webpackts && npm install". I think the package name is incorrect. Was this supposed to be "webpack"? There exists a "webpacks", plural, in npm as well. I assume it is the first.
3. After installing webpack and running npm install, running webpack --config=webpack.dll.js fails because I don't have a valid config.json. Do the values in this config.json file need to be set to my own GCLOUD values? Or are some values shared?
4. I also noticed that run.sh uses tmux. Is this a requirement for running the project? Or is this just a convenience script?

That is as far as I have gotten so far!

**Comment by toddmedema** [comment]
1. Ah yep, turns out Git didn't actually push. Fixed!
2. Typo - should be `webpack`. Fixed!
3. You'll need to make your own GCLOUD project to get your own API keys. I've added a note as such to the README
4. `run.sh` is a convenience script, no tmux needed!

Thank you :)

**Comment by toddmedema** [comment]
Hey @robw2000 ! Anything we can do to help with finishing getting you set up?

**Comment by toddmedema** [comment]
@robw2000 following up here, haven't heard back from you in a while :)

**Comment by robw2000** [comment]
Sorry! I haven't had any spare time to work on this for a while. I will let
you know if I run into any further issues though.

Thanks and keep up the good work!
Rob

**Comment by toddmedema** [comment]
Closing this issue for now, sounds like there haven't been any other issues :) (Feel free to comment here or open a new issue if you do run into any problems!)
